baseurl = "https://satoshun.github.io"
languageCode = "ja"
title = "stsnブログ"
theme = "hyde"
copyright = "Sato Shun"
publishDir = "docs"

[Author]
	name = "Sato Shun"
	bio = "Androidえんじにあー"

[Permalinks]
	blog = "/:year/:month/:filename/"
	book = "/:year/:month/:filename/"
	hobby = "/:year/:month/:filename/"
	gallery = "/:year/:month/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Android, Python, Reactive, DB(RDS), etc"
	twitter = "https://twitter.com/stsn_jp"
	github = "https://github.com/satoshun"
	gplus = "https://plus.google.com/102988556020375542271"
	icon = "https://satoshun.github.io/icon.png"
