baseurl = "http://satoshun.github.io"
languageCode = "ja"
title = "プログラムーン"
theme = "hyde"
copyright = "Sato Shun"

[Author]
	name = "Sato Shun"

[Permalinks]
	blog = "/:year/:month/:filename/"
	book = "/:year/:month/:filename/"
	hobby = "/:year/:month/:filename/"
	gallery = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Android, Python, Reactive, DB(RDS), etc"
	twitter = "https://twitter.com/ss_114514"
	github = "https://github.com/satoshun"
	gplus = "https://plus.google.com/102988556020375542271"
