baseurl = "http://blog.s-shun.net/"
languageCode = "ja"
title = "プログラムーン"
theme = "hyde"
copyright = "Sato Shun"

[Author]
	name = "Sato Shun"

[Permalinks]
	blog = "/:year/:month/:filename/"
	book = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Android, Python, Reactive, DB関連を書きます"
	twitter = "https://twitter.com/satoshun_xyz"
	github = "https://github.com/satoshun"
	gplus = "https://plus.google.com/102988556020375542271"
