baseurl = "https://satoshun.github.io"
languageCode = "ja"
title = "stsnブログ"
theme = "hyde"
copyright = "Sato Shun"
publishDir = "../"

[Author]
	name = "Sato Shun"
	bio = "あんどろいどでぃべろっぱぁー🍎"

[Permalinks]
	blog = "/:year/:month/:filename/"
	book = "/:year/:month/:filename/"
	presentation = "/:year/:month/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "Android, Kotlin, Python, Go, Developer"
	twitter = "https://twitter.com/stsn_jp"
	github = "https://github.com/satoshun"
	gplus = "https://plus.google.com/102988556020375542271"
	icon = "https://bit.ly/2S8StSM"
